version: '3.8'

services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"  # Mapeamento da porta 8080 do host para a porta 80 do contêiner
    env_file:
      - .env
#     networks:
#       - app_network

# networks:
#   app_network:
#     driver: bridge
